services:
  github-actions-runner:
    image: evl8/esd-github-actions-runner
    environment:
      - URL=https://github.com/Anil-Topal/esd-github-actions-assignment
      - TOKEN=AQ4Z5QOCGZJ2KDQOL6ZUYP3HJWPRI
    networks:
      - esd
  nexus:
    image: sonatypecommunity/nexus3
    ports:
    - "8081:8081"
    networks:
      - esd
networks:
  esd:
    driver: bridge